name: jalaninaja_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.1 # or latest version
  http: ^1.2.1 # or latest version
  location: ^5.0.3 # or latest version
  flutter_polyline_points: ^2.0.0 # or latest version
  flutter_typeahead: ^5.2.0 # or latest version
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.0 # Untuk interaksi dengan Supabase
  google_sign_in: ^6.2.1   # Untuk alur login Google
  image_picker: ^1.0.4 # atau versi terbaru
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add this assets section
  assets:
    - assets/map_style.json
    - .env.dev
    - .env.prod
